### ISSUE TITLE
Test/Integration Environment

### ISSUE THREAD

**Issue by jstsddg** [SAKPaaS/deployment#1]
Um Downtime und Probleme beim Deployment zu vermeiden, sollten wir eine Integrations Umgebung schaffen, in der das neue Deployment getestet werden kann.

**Comment by jstsddg** [comment]
Insgesamt könnten mehrere Umgebungen das Entwicklen bereinfachen. Siehe #3.

**Comment by jstsddg** [comment]
Leider haben wir nicht genügend Backend-Services in unserem gCloud plan, damit wir für alles auch eine Dev-Umgebung erstellen können. Vielleicht finden wir enen workaround

**Comment by r-franzke** [comment]
Für Frontend und Backend jeweils Prod und Dev sollte es ja reichen oder?

**Comment by jstsddg** [comment]
Theoretisch ja, aber ich glaube nicht, dass gerade alle Umgebungen erreichbar sind. Der Ingress meldet:
```
  Type     Reason  Age                   From                     Message
  ----     ------  ----                  ----                     -------
  Warning  Sync    9m40s (x56 over 39h)  loadbalancer-controller  Error during sync: error running backend syncing routine: googleapi: Error 403: QUOTA_EXCEEDED - Quota 'BACKEND_SERVICES' exceeded.  Limit: 5.0 globally.
```

**Comment by jstsddg** [comment]
Außerdem:
```
Annotations:
  ingress.kubernetes.io/backends:                    {"k8s-xx-1:"HEALTHY","k8s-xx-2":"HEALTHY","k8s-xx-3":"HEALTHY","k8s-xx-4":"HEALTHY","k8s-xx-5":"UNHEALTHY"}
```

**Comment by DavidSchmidt00** [comment]
@RobSpot-Gaming ist das damit done?

**Comment by r-franzke** [comment]
Ich bin dafür wir nehmen Grafana offline und dafür die Entwicklungsumgebung online oder?

![image](https://user-images.githubusercontent.com/35638696/77916630-a4488400-7299-11ea-9722-3b5d54bbdbe7.png)

**Comment by DavidSchmidt00** [comment]
Dev Frontend
Prod Frontend
Dev Backend
Prod Backend
Welcome

**Comment by r-franzke** [comment]
Alle gewünschten Umgebungen sind deployed:

Frontend: happyhamster.org
Frontend Dev: dev.happyhamster.org

Backend: api.happyhamster.org
Backend Dev: api.dev.happyhamster.org

Welcome: welcome.happyhamster.org
