### ISSUE TITLE
Erstellung einer Prod Integration Umgebung für das Frontend

### ISSUE THREAD

**Issue by r-franzke** [SAKPaaS/deployment#11]
Als Frontend Entwickler ist es mir wichtig, meine Applikation vor dem Deployment in der Produktiv-Umgebung in einer, der Produktion nach empfundenen Umgebung, testen zu können.

**Comment by jstsddg** [comment]
@SAKPaaS/frontend
Wir empfehlen git flow. Dabei würden der development branch in einer dev Umgebung laufen, der master branch in einer Integrations Umgebung laufen und alle releases in der Prod Umgebung.
