### ISSUE TITLE
Automatisierte Deployments

### ISSUE THREAD

**Issue by jstsddg** [SAKPaaS/deployment#3]
Ich als Entwickler möchte, dass meine Releases automatisch deployt werden, damit ich auf @RobSpot-Gaming oder @MrKraboom warten mussen, bis sie das Deployment ausführen.

**Comment by jstsddg** [comment]
Idee:
- Alle Commits des Master werden automatisch gebaut und in eine Test Umgebung deployt.
- Alle Releases werden automatisch gebaut und in die Produktiv Umgebung deployt.

**Comment by r-franzke** [comment]
Klingt gut, ich mach mir mal Gedanken 👍

**Comment by DavidSchmidt00** [comment]
Aber lohnt sich es, das ganze für unsere jetzige Umgebung aufzubauen?! 
Wir bleiben ja eh perspektivisch nicht bei Google.

**Comment by r-franzke** [comment]
Ich hätte direkt damit angefangen eine ganz neue Umgebung einzurichten. Und
wenn alles läuft um zu ziehen. Bis dahin einfach weniger Releases :P

**Comment by jstsddg** [comment]
Hier ist ein Tutorial für einen Zertifikat Manager in Kubernetes, der Let's Encrypt benutzt.
[Digital Ocean Tutorial](https://www.digitalocean.com/community/tutorials/how-to-set-up-an-nginx-ingress-with-cert-manager-on-digitalocean-kubernetes).

**Comment by jstsddg** [comment]
Das sollte in jedem Kubernetes Cluster funktionieren.

**Comment by jstsddg** [comment]
@RobSpot-Gaming Kann man für SAKPaaS auf Docker Hub einen technischen User oder ähnliches erstellen? Ich habe nichts gefunden

**Comment by r-franzke** [comment]
Nicht dass ich wüsste, habe jetzt nur für mich einen API Key erstellen können.

**Comment by jstsddg** [comment]
- Implementierung für [SAKPaaS/backend](/SAKPaaS/backend) ist fertig.
- Implementierung für [SAKPaaS/frontend](/SAKPaaS/frontend) muss noch linting fehler fixen. SAKPaaS/frontend#76
- Implementierung fur [SAKPaaS/welcome](/SAKPaaS/welcome) fehlt.

**Comment by jstsddg** [comment]
Implementierung für [SKAPaaS/welcome](/SAKPaaS/welcome) ist fertig.

**Comment by jstsddg** [comment]
Wir scheinen eine Quota erreicht zu haben:
`kubectl describe ingresses`
Error 403: QUOTA_EXCEEDED - Quota 'BACKEND_SERVICES' exceeded.  Limit: 5.0 globally.

**Comment by jstsddg** [comment]
Implemented!
