### ISSUE TITLE
Persistente Datenspeicherung

### ISSUE THREAD

**Issue by DavidSchmidt00** [SAKPaaS/deployment#5]

**Comment by jstsddg** [comment]
@RobSpot-Gaming wir sollten drei persistent volume claims erstellen.

- Prometheus
- Datenbank
- Grafana config

**Comment by r-franzke** [comment]
Ich fange mal mit Grafana an

**Comment by r-franzke** [comment]
@MrKraboom Guck du dir mal das Grafana Deployment an. Ich bekomme es nicht hin, dass der Storage nicht "readonly" ist.

**Comment by jstsddg** [comment]
Ich schaue Mal ob ich was entdecke

**Comment by jstsddg** [comment]
`/etc/grafana/provisioning/datasources` wird immer read-only sein, weil das von einer config-map kommt und die können nur read-only gemountet sein. Soweit ich weiß.
@RobSpot-Gaming

**Comment by r-franzke** [comment]
@MrKraboom Meinst du also mein pvc ist ReadOnly weil ivh eine ConfigMap nei packe? Das könnt ja sogar sein :P

**Comment by jstsddg** [comment]
Ich schaue mir die Pfade nochmal an. Also eigentlich müsste dann nur der config map Pfad read only sein 🤔

**Comment by jstsddg** [comment]
`​/var/lib/grafana` dürfte eigentlich nicht read-only sein, da der gar nichts mit der config-map zu tun hat... @RobSpot-Gaming

**Comment by jstsddg** [comment]
Aber ich habe eine Idee, habe ich gestern irgendwo gelesen:
Da wir ein Deployment statt ein StatefullSet benutzen, will kubernetes bei jedem Update zuerst den neuen Pod spawnen und starten bevor der alte Pod gekillt wird.. Dadurch kommen wir aber in einen Deadlock, da wir ein ReadWriteOnce PVC haben und der nicht freigegeben wird, bevor der alte Pod weg ist.
@RobSpot-Gaming könnte das passiert sein?

**Comment by r-franzke** [comment]
Si, probiere ich nacher

**Comment by DavidSchmidt00** [comment]
Oh shit jz wirds aber kompliziert 😂

**Comment by r-franzke** [comment]
Okey selbst ohne die ConfigMap und als StatefulSet will des Ding net starten...

**Comment by r-franzke** [comment]
Bin mit meinem Latein am Ende

**Comment by r-franzke** [comment]
Added PVC to Postgres Dev... Right now Testing

**Comment by r-franzke** [comment]
Persistent Storage für Postgres und Postgres Dev funktionieren. Ich habe beschlossen, dass Prometheus und Grafana erstmal nicht wichtig sind.

**Comment by DavidSchmidt00** [comment]
Jap seh ich auch so, da wir ja auch garnicht mehr so viele Services haben
