### ISSUE TITLE
Verify domain

### ISSUE THREAD

**Issue by DavidSchmidt00** [SAKPaaS/deployment#6]
https://github.com/orgs/SAKPaaS/domain/MDE4Ok9yZ2FuaXphdGlvbkRvbWFpbjcxODk0/verification_steps

![verify](https://user-images.githubusercontent.com/43894937/77308402-303b3880-6cfb-11ea-9c2c-3abebab37068.PNG)

**Comment by r-franzke** [comment]
Antwort von Strato:
![image](https://user-images.githubusercontent.com/35638696/77860678-afa39d00-7210-11ea-9a86-0c6090b54976.png)
@DavidSchmidt00 Soll ich da weiter dranbleiben und die nerven oder ist das nicht so wichtig?

**Comment by jstsddg** [comment]
Ich habe mal folgendes versucht:
![image](https://user-images.githubusercontent.com/1850971/77860860-d31b1780-7211-11ea-93ca-3a88d96f1795.png)

**Comment by jstsddg** [comment]
Fertig.
![image](https://user-images.githubusercontent.com/1850971/77860900-05c51000-7212-11ea-9ba7-51825c27c8d1.png)
