### ISSUE TITLE
OpenStreetMap API aufsetzen

### ISSUE THREAD

**Issue by r-franzke** [SAKPaaS/deployment#9]

**Comment by r-franzke** [comment]
@DavidSchmidt00 Der jetzige Server ist nur zu Evaluierungs. Zwecken gedacht und baut Wasserzeichen ein. Gibt es noch einen weiteren Server oder sollen wir die Idee erstmal verwerfen?

**Comment by r-franzke** [comment]
map.happyhamster.org

**Comment by DavidSchmidt00** [comment]
Ja lasst das erstma ruhen
